baseURL = "https://courseswyn.com/"
languageCode = "en-us"
title = "CoursesWyn - Best Udemy Courses & Reviews"
theme = "terminal"
timeZone = "Asia/Jakarta"

# SEO Configuration
[params]
  env = "production"
  description = "Discover the best online courses and expert reviews for 2025. Learn programming, data science, AI, and more with our curated course recommendations."
  author = "CoursesWyn Team"
  keywords = "udemy courses, online learning, programming courses, data science, python courses, best online courses 2025"
  github_url = "https://github.com/Coutons/courseswyn-hugo"
  
  # SEO Features
  enableSEO = true
  enableOpenGraph = true
  enableTwitterCards = true
  
  mainSections = ["post"]
  enablePostNavigationLinks = true
  showAuthor = false
  showCategories = false
  
  # Social Links
  [[params.social]]
    name = "github"
    url = "https://github.com/Coutons"
    
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/CoursesGift"
    
  [[params.social]]
    name = "facebook"
    url = "https://facebook.com/BestCouponPromo"
    
  [[params.social]]
    name = "youtube"
    url = "https://youtube.com/@courseswyn"
    
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/company/courseswyn"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

# Permalinks
[permalinks]
  post = "/:slug/"
  page = "/:slug/"

# Sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    smartypants = true
    fractions = true
    superscript = true
    unsafe = true

# SEO Meta Tags and Schema.org structured data
[params.seo]
  robots = "index, follow"
  googlebot = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
  bingbot = "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"

# Open Graph / Facebook
[params.openGraph]
  enable = true
  defaultImage = "/images/og-image.png"

# Twitter Cards
[params.twitterCards]
  enable = true
  card = "summary_large_image"
  site = "@CoursesGift"
  creator = "@CoursesGift"

# Analytics (add your IDs here)
[params.analytics]
  google_analytics = ""
  google_search_console = ""
