baseURL = "https://courseswyn.com/"
languageCode = "en-us"
title = "CoursesWyn"
theme = "terminal"
timeZone = "Asia/Jakarta"

[params]
  description = "Best Udemy courses and expert reviews"

  [[params.social]]
    name = "github"
    url = "https://github.com/Coutons"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/CoursesGift"

  [[params.social]]
    name = "youtube"
    url = "https://youtube.com/@courseswyn"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/company/courseswyn"

  [[params.social]]
    name = "facebook"
    url = "https://facebook.com/BestCouponPromo"
